[package]
name = "planetdraw-rs"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "packages/celestial_renderer",
    "packages/common_util",
    "packages/core",
    "packages/ecs",
    "packages/input",
    "packages/math",
    "packages/planet_generator/library",
    "packages/planet_generator/binary",
    "packages/real_physics_engine",
    "packages/renderer_common",
    "packages/ui_renderer",
    "packages/universe_simulation",
    "packages/tcpapi",
    "packages/config",
    "packages/media_provider", "packages/celestial_tessellation_provider",
]

[profile.dev.package.planet_generator_library]
opt-level = 3

[workspace.dependencies]
winit = { version = "0.30.7", features = ["rwh_06", "serde"] }
dashu-float = { version = "0.4.3" }
glam = { version = "0.32.0", features = ["serde"] }
ash = { version = "0.38.0", features = ["loaded"] }
ash-window = "0.13.0"
rayon = "1.11.0"
regex = "1.11.1"
gilrs = { version = "0.11.0", features = ["serde-serialize"] }
brotli = "7.0.0"
clap = { version = "4.5.23", features = ["derive"] }
image = "0.25.5"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
rand_xoshiro = "0.8.0"
thiserror = "2.0.11"
fontdue = "0.9.2"
embedded-graphics = "0.8.1"
ts-rs = "11.1"

vengine-rs = { path = "packages/vengine" }
celestial_renderer = { path = "packages/celestial_renderer" }
common_util = { path = "packages/common_util" }
core = { path = "packages/core" }
ecs = { path = "packages/ecs" }
input = { path = "packages/input" }
math = { path = "packages/math" }
planet_generator_library = { path = "packages/planet_generator/library" }
real_physics_engine = { path = "packages/real_physics_engine" }
renderer_common = { path = "packages/renderer_common" }
ui_renderer = { path = "packages/ui_renderer" }
universe_simulation = { path = "packages/universe_simulation" }
tcpapi = { path = "packages/tcpapi" }
config = { path = "packages/config" }
media_provider = { path = "packages/media_provider" }

[dependencies]
glam = { workspace = true, features = ["serde"] }
vengine-rs = { workspace = true }
winit = { workspace = true, features = ["rwh_06", "serde"] }
core = { path = "packages/core" }
config = { workspace = true }
tcpapi = { workspace = true }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { workspace = true }
ts-rs = "11.1"

