#version 460
#extension GL_ARB_separate_shader_objects : enable

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D additiveRGB;
layout(set = 0, binding = 1) uniform sampler2D alphaRGBA;
layout(set = 0, binding = 2, rgba16f) uniform restrict image2D outColor; // the restrict might bite my ass

void main() {
    uvec3 executionSize = gl_NumWorkGroups * gl_WorkGroupSize;
    ivec2 iUV = ivec2(gl_GlobalInvocationID.xy);
    vec2 UV = vec2(gl_GlobalInvocationID.xy) / vec2(executionSize.xy);

    vec4 bbdata = imageLoad(outColor, iUV);
    vec4 additive = texture(additiveRGB, UV).rgba;
    vec4 alpha = texture(alphaRGBA, UV).rgba;

    vec3 color = bbdata.rgb * (1.0 - alpha.a) + additive.rgb + alpha.rgb;

    color.r += 1.0;

    imageStore(outColor, iUV, vec4(color, 1.0));
}
