#version 460
#extension GL_ARB_separate_shader_objects : enable

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

#include "include/compute-uv-coordinates.glsl"

layout(set = 0, binding = 0, rgba16f) uniform restrict image2D additiveRGB;
layout(set = 0, binding = 1, rgba16f) uniform restrict image2D alphaRGBA;
layout(set = 0, binding = 2, rgba16f) uniform restrict image2D outColor; // the restrict might bite my ass

void main() {
    vec4 bbdata = imageLoad(outColor, iUV);
    vec4 additive = imageLoad(additiveRGB, iUV).rgba;
    vec4 alpha = imageLoad(alphaRGBA, iUV).rgba;

    vec3 color = bbdata.rgb * (1.0 - alpha.a) + additive.rgb + alpha.rgb;

    imageStore(outColor, iUV, vec4(color, 1.0));
}
