#version 460
#extension GL_ARB_separate_shader_objects : enable

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform ubo {
    float exposure;
    int debugTextureIndex;
} uniforms;

float exposure = uniforms.exposure;
int debugTextureIndex = uniforms.debugTextureIndex;

layout(set = 0, binding = 1) uniform sampler2D celestialResultTexture;
layout(set = 0, binding = 2, rgba16f) uniform restrict image2D outColor; // the restrict might bite my ass
layout(set = 0, binding = 3) uniform sampler2D debugTexture1;
layout(set = 0, binding = 4) uniform sampler2D debugTexture2;
layout(set = 0, binding = 5) uniform sampler2D debugTexture3;
layout(set = 0, binding = 6) uniform sampler2D debugTexture4;

vec3 aces_tonemap(vec3 color){	
	mat3 m1 = mat3(
        0.59719, 0.07600, 0.02840,
        0.35458, 0.90834, 0.13383,
        0.04823, 0.01566, 0.83777
	);
	mat3 m2 = mat3(
        1.60475, -0.10208, -0.00327,
        -0.53108,  1.10813, -0.07276,
        -0.07367, -0.00605,  1.07602
	);
	vec3 v = m1 * color;    
	vec3 a = v * (v + 0.0245786) - 0.000090537;
	vec3 b = v * (0.983729 * v + 0.4329510) + 0.238081;
	return pow(clamp(m2 * (a / b), 0.0, 1.0), vec3(1.0 / 2.2));	
}

void main() {
    uvec3 executionSize = gl_NumWorkGroups * gl_WorkGroupSize;
    ivec2 iUV = ivec2(gl_GlobalInvocationID.xy);
    vec2 UV = vec2(gl_GlobalInvocationID.xy) / vec2(executionSize.xy);

    vec4 color = vec4(0.0);

    if(debugTextureIndex == 1) { color = vec4(texture(debugTexture1, UV).rgb, 1.0); }
    else if(debugTextureIndex == 2) { color = vec4(texture(debugTexture2, UV).rgb, 1.0); }
    else if(debugTextureIndex == 3) { color = vec4(texture(debugTexture3, UV).rgb, 1.0); }
    else if(debugTextureIndex == 4) { color = vec4(texture(debugTexture4, UV).rgb, 1.0); }
    else { 
        vec4 celestialResult = texture(celestialResultTexture, UV);
        color = vec4(aces_tonemap(celestialResult.rgb * exposure), 1.0);
    }
    
    imageStore(outColor, iUV, color);
}
