#version 460
#extension GL_ARB_separate_shader_objects : enable

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

#include "include/compute-uv-coordinates.glsl"

layout(set = 0, binding = 0) uniform ubo {
    float exposure;
} uniforms;

float exposure = uniforms.exposure;

layout(set = 0, binding = 1, rgba16f) uniform restrict image2D celestialResultTexture;
layout(set = 0, binding = 2, rgba16f) uniform restrict image2D uiResult;
layout(set = 0, binding = 3, rgba16f) uniform restrict image2D outColor; // the restrict might bite my ass

vec3 aces_tonemap(vec3 color){	
	mat3 m1 = mat3(
        0.59719, 0.07600, 0.02840,
        0.35458, 0.90834, 0.13383,
        0.04823, 0.01566, 0.83777
	);
	mat3 m2 = mat3(
        1.60475, -0.10208, -0.00327,
        -0.53108,  1.10813, -0.07276,
        -0.07367, -0.00605,  1.07602
	);
	vec3 v = m1 * color;    
	vec3 a = v * (v + 0.0245786) - 0.000090537;
	vec3 b = v * (0.983729 * v + 0.4329510) + 0.238081;
	return pow(clamp(m2 * (a / b), 0.0, 1.0), vec3(1.0 / 2.2));	
}

void main() {
    // // make final flip
    // vec4 celestialResult = texture(celestialResultTexture, vec2(UV.x, 1.0 - UV.y));
    
    vec4 celestialResult = imageLoad(celestialResultTexture, iUV);
    vec4 color = vec4(aces_tonemap(celestialResult.rgb * exposure), 1.0);
    
    vec4 ui = imageLoad(uiResult, iUV);
    color = mix(color, ui, ui.a);

    color.a = 1.0;
    
    imageStore(outColor, iUV, color);
}
