// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachedComponents } from "./AttachedComponents.js";

export type AddEntityInput = { components: AttachedComponents | null };
