// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeshComponent } from "./MeshComponent.js";

export type AddMeshComponentInput = {
  entityId: string;
  component: MeshComponent;
};
