// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetPhysicsKinematicsComponent } from "./SetPhysicsKinematicsComponent.js";

export type AddSetPhysicsKinematicsInput = {
  entityId: bigint;
  component: SetPhysicsKinematicsComponent;
};
