// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entity } from "./Entity.js";
import type { TimeCounter } from "./TimeCounter.js";

export type ECSWorldSerializedRepresentation = {
  entities: Array<Entity>;
  timeCounter: TimeCounter;
};
