// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachedComponents } from "./AttachedComponents.js";

export type Entity = {
  id: number;
  name: string | null;
  components: AttachedComponents;
};
