// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Components } from "./Components.js";

export type FindAllEntitiesByComponents = { components: Array<Components> };
