// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FirstPersonCameraControlComponent } from "./FirstPersonCameraControlComponent.js";

export type SetFirstPersonCameraControlComponentInput = {
  entityId: string;
  component: FirstPersonCameraControlComponent;
};
