// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RealPhysicsComponent } from "./RealPhysicsComponent.js";

export type SetRealPhysicsInput = {
  entityId: number;
  component: RealPhysicsComponent;
};
