// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SimplePhysicsComponent } from "./SimplePhysicsComponent.js";

export type SetSimplePhysicsComponentInput = {
  entityId: string;
  component: SimplePhysicsComponent;
};
