// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShipControlComponent } from "./ShipControlComponent.js";

export type SetShipControlInput = {
  entityId: number;
  component: ShipControlComponent;
};
