// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransformComponent } from "./TransformComponent.js";

export type SetTransformComponentInput = {
  entityId: string;
  component: TransformComponent;
};
