// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThirdPersonOrbitCameraControlComponent } from "./ThirdPersonOrbitCameraControlComponent.js";

export type SetThirdPersonOrbitCameraControlInput = {
  entityId: bigint;
  component: ThirdPersonOrbitCameraControlComponent;
};
