// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThirdPersonStaticCameraControlComponent } from "./ThirdPersonStaticCameraControlComponent.js";

export type SetThirdPersonStaticCameraControlInput = {
  entityId: bigint;
  component: ThirdPersonStaticCameraControlComponent;
};
