// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThirdPersonStaticCameraControlComponent } from "./ThirdPersonStaticCameraControlComponent.js";

export type SetThirdPersonStaticCameraControlComponentInput = {
  entityId: string;
  component: ThirdPersonStaticCameraControlComponent;
};
