// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UIHoverColorComponent } from "./UIHoverColorComponent.js";

export type SetUIHoverColorComponentInput = {
  entityId: string;
  component: UIHoverColorComponent;
};
