// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UITextureComponent } from "./UITextureComponent.js";

export type SetUITextureInput = {
  entityId: number;
  component: UITextureComponent;
};
