// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UIColorComponent } from "./UIColorComponent.js";

export type SetUIColorComponentInput = {
  entityId: string;
  component: UIColorComponent;
};
