// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UIHoverCursorComponent } from "./UIHoverCursorComponent.js";

export type SetUIHoverCursorComponentInput = {
  entityId: string;
  component: UIHoverCursorComponent;
};
