// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UIBoxComponent } from "./UIBoxComponent.js";

export type SetUIBoxComponentInput = {
  entityId: string;
  component: UIBoxComponent;
};
