// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UniverseClockComponent } from "./UniverseClockComponent.js";

export type SetUniverseClockInput = {
  entityId: bigint;
  component: UniverseClockComponent;
};
