// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SimplePhysicsComponent = {
  id: number;
  mass: string;
  linear_velocity: [number, number, number];
  angular_velocity: [number, number, number];
};
