// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThirdPersonStaticCameraControlComponent = {
  id: bigint;
  fov: number;
  offset: [number, number, number];
  orientation: [number, number, number, number];
};
