// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecimalVector3d } from "./DecimalVector3d.js";

export type TransformComponent = {
  id: bigint;
  position: DecimalVector3d;
  orientation: [number, number, number, number];
  scale: [number, number, number];
};
