// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UIFontSize } from "./UIFontSize.js";

export type UITextComponent = {
  id: bigint;
  content: string;
  color: [number, number, number, number];
  font_size: UIFontSize;
};
