#version 460
#extension GL_ARB_separate_shader_objects : enable

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

#include "include/compute-uv-coordinates.glsl"

layout(set = 0, binding = 0) uniform ubo {
    vec4 seed;
    vec4 elapsed_frequency_zero_zero;
} uniforms;
layout(set = 0, binding = 1, r16f) uniform restrict image2D outColor; // the restrict might bite my ass

vec3 seed = uniforms.seed.xyz;
float elapsed = uniforms.elapsed_frequency_zero_zero.x;
float frequency = uniforms.elapsed_frequency_zero_zero.y;

#include "include/polar.glsl"
#include "include/noise/super-3d.glsl"

float cloudsFBM(vec3 p, int iterations){
    float a = 0.0;
    float w = 0.5;
    for(int i=0;i<iterations;i++){
        float x = abs(0.5 - supernoise3D(p))*2.0;
        a += x * w;
        p = p * 2.9 + p * a * 0.001;
        w *= 0.60;
    }
    return a;
}

void main() {
    vec3 normal = normalize(polarToXyz(UV));
    float result = cloudsFBM(normal * frequency + seed.xyz + elapsed * 0.00001, 8);
    imageStore(outColor, iUV, vec4(0.0, 0.0, 0.0, 0.0));
}
