#version 460
#extension GL_ARB_separate_shader_objects : enable

layout(set = 0, binding = 0) uniform ubo {
    vec4 seed;
    vec4 elapsed_frequency_zero_zero;
} uniforms;

vec3 seed = uniforms.seed.xyz;
float elapsed = uniforms.elapsed_frequency_zero_zero.x;
float frequency = uniforms.elapsed_frequency_zero_zero.y;

layout(set = 0, binding = 1, r32f) uniform writeonly image3D outputImage;

float afloct(vec3 p, float tile){
    p = mod(p, tile);
    return fract(4768.1232345456 * sin((p.x+p.y*43.0+p.z*137.0)));
}

float aflnoisetile(vec3 x, float tile){
    vec3 p = floor(x);
    vec3 fr = smoothstep(0.0, 1.0, fract(x));
    vec3 LBZ = p + vec3(0.0, 0.0, 0.0);
    vec3 LTZ = p + vec3(0.0, 1.0, 0.0);
    vec3 RBZ = p + vec3(1.0, 0.0, 0.0);
    vec3 RTZ = p + vec3(1.0, 1.0, 0.0);

    vec3 LBF = p + vec3(0.0, 0.0, 1.0);
    vec3 LTF = p + vec3(0.0, 1.0, 1.0);
    vec3 RBF = p + vec3(1.0, 0.0, 1.0);
    vec3 RTF = p + vec3(1.0, 1.0, 1.0);

    float l0candidate1 = afloct(LBZ, tile);
    float l0candidate2 = afloct(RBZ, tile);
    float l0candidate3 = afloct(LTZ, tile);
    float l0candidate4 = afloct(RTZ, tile);

    float l0candidate5 = afloct(LBF, tile);
    float l0candidate6 = afloct(RBF, tile);
    float l0candidate7 = afloct(LTF, tile);
    float l0candidate8 = afloct(RTF, tile);

    float l1candidate1 = mix(l0candidate1, l0candidate2, fr[0]);
    float l1candidate2 = mix(l0candidate3, l0candidate4, fr[0]);
    float l1candidate3 = mix(l0candidate5, l0candidate6, fr[0]);
    float l1candidate4 = mix(l0candidate7, l0candidate8, fr[0]);


    float l2candidate1 = mix(l1candidate1, l1candidate2, fr[1]);
    float l2candidate2 = mix(l1candidate3, l1candidate4, fr[1]);

    float l3candidate1 = mix(l2candidate1, l2candidate2, fr[2]);

    return l3candidate1;
}

float aflsupernoise3dtile(vec3 p, float tile){
	float a = aflnoisetile(p, tile);
	float b = aflnoisetile(p + 120.5, tile);
	return (a * b);
}

float cloudsFBM(vec3 p, int iterations){
    float a = 0.0;
    float w = 0.5;
    float tile = 64.0;
    for(int i=0;i<iterations;i++){
        float x = abs(0.5 - aflsupernoise3dtile(p, tile))*2.0;
        a += x * w;
        p = p * 2.9;// + p * a * 0.001;
        w *= 0.60;
        tile *= 2.9;
    }
    return a;
}

layout(local_size_x = 32, local_size_y = 32, local_size_z = 32) in;

void main() {
    vec3 coord = vec3(gl_GlobalInvocationID) / 64.0;
    float result = cloudsFBM(coord * frequency + seed.xyz, 8);
    imageStore(outputImage, ivec3(gl_GlobalInvocationID), vec4(result, 0.0, 0.0, 0.0));
}
