// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScaledTextureDescription } from "./ScaledTextureDescription";

export type ColorOrTextureDescription =
  | { color: [number, number, number] }
  | { texture: ScaledTextureDescription };
