// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachedComponents } from "./AttachedComponents";

export type CreateEntityInput = {
  name: string | null;
  components: AttachedComponents;
};
