// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorOrTextureDescription } from "./ColorOrTextureDescription";
import type { ScaledTextureDescription } from "./ScaledTextureDescription";
import type { ValueOrTextureDescription } from "./ValueOrTextureDescription";

export type MaterialDescription = {
  color: ColorOrTextureDescription;
  roughness: ValueOrTextureDescription;
  metalness: ValueOrTextureDescription;
  emission: ColorOrTextureDescription;
  normal: ScaledTextureDescription | null;
  bump: ScaledTextureDescription | null;
};
