// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MaterialDescription } from "./MaterialDescription";

export type MeshDescription = {
  geometryPath: string;
  material: MaterialDescription;
};
