// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShapeDescription } from "./ShapeDescription";

export type RealPhysicsComponent = {
  id: bigint;
  shape_description: ShapeDescription;
};
