// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BallColliderDescription } from "./BallColliderDescription";
import type { BoxColliderDescription } from "./BoxColliderDescription";
import type { ConeColliderDescription } from "./ConeColliderDescription";
import type { CylinderColliderDescription } from "./CylinderColliderDescription";

export type ShapeDescription =
  | { ball: BallColliderDescription }
  | { box: BoxColliderDescription }
  | { cylinder: CylinderColliderDescription }
  | { cone: ConeColliderDescription };
